# Generated by Django 5.2.2 on 2025-06-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinera', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='cedula',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='productos',
            field=models.CharField(default='productos', max_length=50, unique=True),
        ),
    ]
