# Generated by Django 5.2 on 2025-05-18 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='nombre',
        ),
    ]
