# Generated by Django 5.2 on 2025-05-18 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_remove_compras_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compras',
            old_name='categoria',
            new_name='productos',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='codigo',
        ),
    ]
