# Generated by Django 5.0.4 on 2025-04-23 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('productos', models.CharField(default='productos', max_length=50)),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('valor', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
